import json
import os
from web3 import Web3

# Connect to local Hardhat node
w3 = Web3(Web3.HTTPProvider('http://127.0.0.1:8545'))

# Ensure connected
if not w3.is_connected():
    print("Warning: Could not connect to local Hardhat node at http://127.0.0.1:8545")

# Load contract address
ADDRESS_FILE = os.path.join(os.path.dirname(__file__), '..', 'contract_address.txt')
if os.path.exists(ADDRESS_FILE):
    with open(ADDRESS_FILE, 'r') as f:
        contract_address = f.read().strip()
else:
    contract_address = None
    print(f"Warning: Contract address file not found at {ADDRESS_FILE}")

# Load ABI
ARTIFACT_FILE = os.path.join(os.path.dirname(__file__), '..', 'blockchain', 'artifacts', 'contracts', 'AnomalyLogger.sol', 'AnomalyLogger.json')
if os.path.exists(ARTIFACT_FILE):
    with open(ARTIFACT_FILE, 'r') as f:
        artifact = json.load(f)
        abi = artifact['abi']
else:
    abi = None
    print(f"Warning: Contract ABI not found at {ARTIFACT_FILE}")

if contract_address and abi:
    contract = w3.eth.contract(address=contract_address, abi=abi)
else:
    contract = None

def log_anomaly_to_blockchain(url, data_hash, timestamp):
    """Logs the anomaly to the blockchain. Uses the first local account."""
    if not contract:
        return {"status": "error", "message": "Smart contract not loaded"}
    
    try:
        # Use the first account generated by hardhat node
        account = w3.eth.accounts[0]
        
        tx_hash = contract.functions.logAnomaly(url, data_hash, int(timestamp)).transact({
            'from': account
        })
        
        # Wait for receipt
        receipt = w3.eth.wait_for_transaction_receipt(tx_hash)
        
        return {
            "status": "success",
            "tx_hash": tx_hash.hex(),
            "block_number": receipt.blockNumber
        }
    except Exception as e:
        return {"status": "error", "message": str(e)}

def get_anomalies():
    if not contract:
        return []
    
    try:
        count = contract.functions.getAnomaliesCount().call()
        anomalies = []
        for i in range(count):
            url, dataHash, timestamp = contract.functions.getAnomaly(i).call()
            anomalies.append({
                "url": url,
                "dataHash": dataHash,
                "timestamp": timestamp
            })
        return anomalies
    except Exception as e:
        print(f"Error fetching anomalies: {e}")
        return []
